const OpenAI = require('openai');

let openai = null;
const hasApiKey = !!process.env.OPENAI_API_KEY && !process.env.OPENAI_API_KEY.startsWith('sk-your');

if (hasApiKey) {
  openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

// ──────────────────────────────────────────────
// Generate a study plan from user inputs
// ──────────────────────────────────────────────
const generateStudyPlan = async ({ subjects, examDate, hoursPerDay, language }) => {
  const daysLeft = Math.ceil((new Date(examDate) - new Date()) / (1000 * 60 * 60 * 24));
  const lang = language === 'am' ? 'Amharic' : 'English';

  const prompt = `
You are an expert academic study planner. A student needs a detailed study schedule.

Subjects (with weak level 1-5):
${subjects.map((s) => `- ${s.name}: weakness level ${s.weakLevel}/5`).join('\n')}

Days until exam: ${daysLeft}
Study hours per day: ${hoursPerDay}
Response language: ${lang}

Create a day-by-day study plan. Return ONLY valid JSON in this exact format:
{
  "title": "string",
  "summary": "string (2-3 sentences motivational overview)",
  "tasks": [
    {
      "subject": "string",
      "topic": "string",
      "date": "YYYY-MM-DD",
      "duration": number (minutes),
      "priority": "low|medium|high",
      "notes": "string"
    }
  ]
}
Generate up to ${Math.min(daysLeft * 3, 30)} tasks spread across the days.
`;

  if (hasApiKey) {
    const res = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [{ role: 'user', content: prompt }],
      response_format: { type: 'json_object' },
      temperature: 0.7,
    });
    return JSON.parse(res.choices[0].message.content);
  }

  // ── MOCK (no API key) ──
  const today = new Date();
  const mockTasks = subjects.flatMap((s, i) =>
    Array.from({ length: Math.min(daysLeft, 5) }, (_, d) => {
      const date = new Date(today);
      date.setDate(date.getDate() + d + i);
      return {
        subject: s.name,
        topic: `Core revision – ${s.name} (Day ${d + 1})`,
        date: date.toISOString().split('T')[0],
        duration: Math.round(hoursPerDay * 60 / subjects.length),
        priority: s.weakLevel >= 4 ? 'high' : s.weakLevel <= 2 ? 'low' : 'medium',
        notes: `Focus on practice problems and key concepts.`,
      };
    })
  );

  return {
    title: `${daysLeft}-Day Exam Prep Plan`,
    summary: `Your personalized study plan covers ${subjects.length} subject(s) over ${daysLeft} days with ${hoursPerDay} hours/day. Prioritize high-weakness subjects first.`,
    tasks: mockTasks,
  };
};

// ──────────────────────────────────────────────
// Answer a question (Q&A system)
// ──────────────────────────────────────────────
const answerQuestion = async ({ question, subject, language }) => {
  const lang = language === 'am' ? 'Amharic' : 'English';

  const prompt = `You are a helpful, knowledgeable tutor. Answer the following student question clearly and concisely in ${lang}.
Subject: ${subject}
Question: ${question}

Provide a well-structured answer with key points. Use simple language appropriate for students.`;

  if (hasApiKey) {
    const res = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.6,
      max_tokens: 600,
    });
    return res.choices[0].message.content;
  }

  const mocks = {
    Mathematics: `Great question! In mathematics, this concept relates to the fundamental principles of the topic. Here are the key points:\n\n1. **Definition**: The core concept can be understood as a systematic approach to problem-solving.\n2. **Key Formula**: Apply the relevant formula step by step.\n3. **Example**: Work through a simple example to verify your understanding.\n4. **Practice Tip**: Solve at least 5 similar problems daily to strengthen this skill.`,
    Physics: `This is an important physics concept! Here's a clear explanation:\n\n1. **Principle**: This phenomenon follows Newton's laws / thermodynamic principles.\n2. **Real-world application**: You can see this in everyday life when...\n3. **Mathematical representation**: The equation governing this is F = ma or similar.\n4. **Remember**: Always check units and directions in physics problems.`,
    default: `Excellent question! Here's a comprehensive answer:\n\n1. **Overview**: This topic is fundamental to understanding the subject matter.\n2. **Key Concepts**: Break down the question into smaller, manageable parts.\n3. **Explanation**: Each component builds on the previous one logically.\n4. **Summary**: Understanding this will help you tackle related problems with confidence.\n\n*This answer was generated by BrainBridge AI. A teacher may review and enhance it.*`,
  };

  return mocks[subject] || mocks.default;
};

// ──────────────────────────────────────────────
// Voice conversation answer
// ──────────────────────────────────────────────
const voiceAnswer = async ({ transcript, language }) => {
  const lang = language === 'am' ? 'Amharic' : 'English';

  const prompt = `You are a friendly AI tutor responding to a student's spoken question. Give a concise, conversational answer in ${lang} (2-4 sentences max, suitable for text-to-speech).

Student asked: "${transcript}"`;

  if (hasApiKey) {
    const res = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 200,
    });
    return res.choices[0].message.content;
  }

  return language === 'am'
    ? 'ጥሩ ጥያቄ! ይህ ርዕስ ለእርስዎ ትምህርት አስፈላጊ ነው። ዋና ዋና ጽንሰ-ሐሳቦችን ለመረዳት ሞክሩ እና ተጨማሪ ማብራሪያ ከፈለጉ ሁልጊዜ ይጠይቁ።'
    : 'Great question! This is a key concept in your studies. The main idea is to break it down step by step and apply the core principles. I recommend reviewing your notes and practicing with similar examples to strengthen your understanding.';
};

// ──────────────────────────────────────────────
// Adjust an existing study plan
// ──────────────────────────────────────────────
const adjustStudyPlan = async ({ title, examDate, remainingTasks, hoursPerDay, language }) => {
  const daysLeft = Math.ceil((new Date(examDate) - new Date()) / (1000 * 60 * 60 * 24));
  const lang = language === 'am' ? 'Amharic' : 'English';

  const prompt = `
You are an expert academic study planner. A student is lagging behind on their study plan "${title}".
They have ${daysLeft} days left until their exam on ${examDate.split('T')[0]}.
They have ${hoursPerDay} hours available per day.

Remaining tasks (including skipped ones):
${remainingTasks.map((t) => `- ${t.subject}: ${t.topic} (Original duration: ${t.duration}m, Status: ${t.status})`).join('\n')}

Create a NEW optimized day-by-day study schedule for the remaining time. 
Redistribute the remaining workload across the available days.
Return ONLY valid JSON in this exact format:
{
  "summary": "string (new motivational overview)",
  "tasks": [
    {
      "subject": "string",
      "topic": "string",
      "date": "YYYY-MM-DD",
      "duration": number (minutes),
      "priority": "low|medium|high",
      "notes": "string"
    }
  ]
}
`;

  if (hasApiKey) {
    const res = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [{ role: 'user', content: prompt }],
      response_format: { type: 'json_object' },
      temperature: 0.7,
    });
    return JSON.parse(res.choices[0].message.content);
  }

  // ── MOCK (no API key) ──
  const today = new Date();
  const mockTasks = remainingTasks.map((t, i) => {
    const date = new Date(today);
    date.setDate(date.getDate() + Math.floor(i / 2));
    return {
      ...t,
      date: date.toISOString().split('T')[0],
      notes: `Rescheduled: ${t.notes || "Focus on key concepts."}`,
    };
  });

  return {
    summary: `I've adjusted your schedule to fit the remaining ${daysLeft} days. Don't worry about the skips—focus on these next steps!`,
    tasks: mockTasks,
  };
};

module.exports = { generateStudyPlan, adjustStudyPlan, answerQuestion, voiceAnswer };
